jobs:
  build:
    docker:
      - image: circleci/node:8.2.1

    working_directory:
      ~/app

    branches:
      only:
        - master

    steps:
      - checkout

      - save_cache:
          key: v1-myapp-cache
          paths:
              - .node_modules

      - run:
          name: "install application"
          command: npm install

      - run:
          name: "test application"
          command: npm test

      - setup_remote_docker

      - run:
          name: "create and push docker image"
          environment:
              DOCKER_HUB_ACCT: pratikadhau
              DOCKER_HUB_REPOSITORY: cts-client
              PASSWORD: Password@123
          command: |
              docker build -t $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:$CIRCLE_BUILD_NUM .
              docker tag  $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:$CIRCLE_BUILD_NUM $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:latest
              docker login -u $DOCKER_HUB_ACCT -p $PASSWORD
              docker push $DOCKER_HUB_ACCT/$DOCKER_HUB_REPOSITORY:$CIRCLE_BUILD_NUM
